### ISSUE TITLE
JSON for Win10 updates is woefully out of date

### ISSUE THREAD

**Issue by cluberti** [stefmsft/SurfUtil#2]
While this used to work and be kept relatively up-to-date, as of late (the last 6+ months) it has become woefully out of date (it doesn't have any RS5 builds, for instance, and RS4 builds are months behind - latest listed is August 2018).

You're better off pulling this from a local WSUS server and getting the URL.  Worst case I suppose you could do something with WSUSSCAN.CAB files, but that seems like much more work.  Just an FYI, you might as well always skip this if you're going to try to use the RSS feed.

**Comment by stefmsft** [comment]
Hi Carl
Not sure to understand. I recently made some change on my queries to the Catalog as the method using 4000816 was outdated. That's still a hack as I'm doing web scrapping but that's easy to verify. Go to the catalog page query type "2019-03 cumulative x64 windows 10 1809" and you Indeed get the latest CU. In may code of course the 2019 varies to stay up to date.
All is in function New-LatestCUUrl - But this conversation was usefull as I found a bug in my function on the way I was handling the returned values (expected an array from my previous test and having now a string because of the more precise querie string). This is all fix on the latest commit made ()
